more infa updates

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -25,14 +25,17 @@ jobs:
       - name: Build Docker image
         run: docker build -t autobike .
 
+      # Build ROS project
+      - name: Build ROS project
+        run: ${{ env.DOCKER_BASE_CMD }} autobike build
+
       # Run Black formatting check
       - name: Black formatting check
-        # always() runs even if the job is canceled, while success() || failure() does not
-        if: success() || failure()
         run: ${{ env.DOCKER_BASE_CMD }} autobike bash -ic "format --check"
 
       # Run Pylint linting
       - name: Pylint linting
+        # always() runs even if the job is canceled, while success() || failure() does not
         if: success() || failure()
         run: ${{ env.DOCKER_BASE_CMD }} autobike bash -ic "lint"
 
