Add ROS! (#49)
* work on unifying CI env

* update README.md

* dir structure changes

* update image for workflow

* format and fix some lint errors

* update workflow and fix some errors in waypoints

* tweaks to documentation and meta data

* Update alerts

* fix some lint errors and other infa changes

* Dockerfile updates

* pin versions

* Automatic linter changes

* Fix most liniting problems

* Fix remaining linting errors

* revert unintended changes

* Fix mypy type check

* correct mypy errors and silence failing test

* revert constants

* fix badge

* upload code cov always and add arch diagram

* fix mermaid colors

* update code coverage workflow

* try to fix coverage again

* last time, I swear

* update arch

* ROS arch

* working novnc

* ROS board

* working docker install... no tkinter tho

* working python and ros

* hodge podge ROS changes

* working waypoint node

* more infa updates

* fix local file pytest and colcon test running

* update ROS info in README

* readme tips

* track OSM map

* update test, no docker cache

* remove demo version

* remove compose version

* fix build github workflow

* attempt to fix permission errors

* run workflow as root

* clean up and fix entrypoint

* fix and ignore lint errors

* readme updates

* fix type_check step

* try one container workflow

* readme tweak

* back to one container per stage

* resolve gitignore conflict

---------

Co-authored-by: Ari Mirsky <arimirsky@gmail.com>

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -13,7 +13,8 @@ jobs:
     # We only need to test on one OS as we are using Docker
     runs-on: ubuntu-latest
     env:
-      DOCKER_BASE_CMD: docker run --user root --rm
+      # Running as root removes permission errors when running github workflow
+      DOCKER_BASE_CMD: docker compose run --rm --user root
       COVERAGE_VOLUME: ${{ github.workspace }}/coverage:/usr/app/coverage
 
     steps:
@@ -23,29 +24,39 @@ jobs:
 
       # Build Docker image
       - name: Build Docker image
-        run: docker build -t autobike .
+        run: docker build -t autobike --no-cache .
+
+      # Build ROS project
+      - name: Build ROS project
+        if: success()
+        run: ${{ env.DOCKER_BASE_CMD }} autobike bash -ic "build"
+
+      # Run test ROS package
+      - name: Run ROS package
+        if: success()
+        run: ${{ env.DOCKER_BASE_CMD }} autobike bash -ic "build && ros2 run waypoints once"
 
       # Run Black formatting check
       - name: Black formatting check
-        # always() runs even if the job is canceled, while success() || failure() does not
         if: success() || failure()
-        run: ${{ env.DOCKER_BASE_CMD }} autobike black --check --config pyproject.toml .
+        run: ${{ env.DOCKER_BASE_CMD }} autobike bash -ic "format_check"
 
       # Run Pylint linting
       - name: Pylint linting
+        # always() runs even if the job is canceled, while success() || failure() does not
         if: success() || failure()
-        run: ${{ env.DOCKER_BASE_CMD }} autobike pylint --rcfile=pyproject.toml src/
+        run: ${{ env.DOCKER_BASE_CMD }} autobike bash -ic "lint"
 
       # Run Pytest with code coverage
       - name: Pytest with code coverage
         if: success() || failure()
         # Specify coverage volume
-        run: ${{ env.DOCKER_BASE_CMD }} -v ${{ env.COVERAGE_VOLUME }} autobike pytest --cov=./ --cov-report=xml:./coverage/coverage.xml --cov-report=term
+        run: ${{ env.DOCKER_BASE_CMD }} -v ${{ env.COVERAGE_VOLUME }} autobike bash -ic "build && pytest --cov=./ --cov-report=xml:./coverage/coverage.xml --cov-report=term"
 
       # Run mypy type checking
       - name: Mypy type check
         if: success() || failure()
-        run: ${{ env.DOCKER_BASE_CMD }} autobike mypy --config-file=pyproject.toml src/
+        run: ${{ env.DOCKER_BASE_CMD }} autobike bash -ic "type_check"
 
       # Upload to codecov
       - name: Upload coverage to Codecov
