fix some lint errors and other infa changes

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -1,4 +1,4 @@
-name: Build
+name: test
 
 on:
   push:
@@ -12,6 +12,8 @@ jobs:
   build:
     # We only need to test on one OS as we are using Docker
     runs-on: ubuntu-latest
+    env:
+      DOCKER_RUN_CMD: docker run --user root --rm autobike:workflow
 
     steps:
       # Checkout code
@@ -24,23 +26,24 @@ jobs:
 
       # Run Black formatting check
       - name: Black formatting check
+        # always() runs even if the job is canceled, while success() || failure() does not
         if: success() || failure()
-        run: docker run --rm autobike:workflow black --check --config pyproject.toml .
+        run: ${{ env.DOCKER_RUN_CMD }} black --check --config pyproject.toml .
 
       # Run Pylint linting
       - name: Pylint linting
         if: success() || failure()
-        run: docker run --rm autobike:workflow pylint --rcfile=pyproject.toml src/
+        run: ${{ env.DOCKER_RUN_CMD }} pylint --rcfile=pyproject.toml src/
 
       # Run Pytest with code coverage
       - name: Pytest with code coverage
         if: success() || failure()
-        run: docker run --rm autobike:workflow pytest --cov=./ --cov-report=xml
+        run: ${{ env.DOCKER_RUN_CMD }} pytest --cov=./ --cov-report=xml
 
       # Run mypy type checking
       - name: Mypy type check
         if: success() || failure()
-        run: docker run --rm autobike:workflow mypy --config-file=pyproject.toml src/
+        run: ${{ env.DOCKER_RUN_CMD }} mypy --config-file=pyproject.toml src/
 
       # Upload to codecov
       - name: Upload coverage to Codecov
